name: CI

on:
  push:
    branches: ["develop", "feature"]
  pull_request:
    branches: ["develop"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' 
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test -- --watchAll=false

      - name: Run ESLint
        run: npm run lint
